// Generated by gencpp from file dwa/goal_requestRequest.msg
// DO NOT EDIT!


#ifndef DWA_MESSAGE_GOAL_REQUESTREQUEST_H
#define DWA_MESSAGE_GOAL_REQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dwa
{
template <class ContainerAllocator>
struct goal_requestRequest_
{
  typedef goal_requestRequest_<ContainerAllocator> Type;

  goal_requestRequest_()
    : bot_name()  {
    }
  goal_requestRequest_(const ContainerAllocator& _alloc)
    : bot_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bot_name_type;
  _bot_name_type bot_name;





  typedef boost::shared_ptr< ::dwa::goal_requestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwa::goal_requestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct goal_requestRequest_

typedef ::dwa::goal_requestRequest_<std::allocator<void> > goal_requestRequest;

typedef boost::shared_ptr< ::dwa::goal_requestRequest > goal_requestRequestPtr;
typedef boost::shared_ptr< ::dwa::goal_requestRequest const> goal_requestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwa::goal_requestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwa::goal_requestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dwa

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dwa::goal_requestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwa::goal_requestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwa::goal_requestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwa::goal_requestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwa::goal_requestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwa::goal_requestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwa::goal_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "538473db0cbbce885b1f9f383e540f13";
  }

  static const char* value(const ::dwa::goal_requestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x538473db0cbbce88ULL;
  static const uint64_t static_value2 = 0x5b1f9f383e540f13ULL;
};

template<class ContainerAllocator>
struct DataType< ::dwa::goal_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwa/goal_requestRequest";
  }

  static const char* value(const ::dwa::goal_requestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwa::goal_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string bot_name\n\
";
  }

  static const char* value(const ::dwa::goal_requestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwa::goal_requestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bot_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goal_requestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwa::goal_requestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwa::goal_requestRequest_<ContainerAllocator>& v)
  {
    s << indent << "bot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bot_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWA_MESSAGE_GOAL_REQUESTREQUEST_H
