// Generated by gencpp from file dwa/GoalRequestResponse.msg
// DO NOT EDIT!


#ifndef DWA_MESSAGE_GOALREQUESTRESPONSE_H
#define DWA_MESSAGE_GOALREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dwa
{
template <class ContainerAllocator>
struct GoalRequestResponse_
{
  typedef GoalRequestResponse_<ContainerAllocator> Type;

  GoalRequestResponse_()
    : goal_x(0)
    , goal_y(0)
    , success(false)  {
    }
  GoalRequestResponse_(const ContainerAllocator& _alloc)
    : goal_x(0)
    , goal_y(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int64_t _goal_x_type;
  _goal_x_type goal_x;

   typedef int64_t _goal_y_type;
  _goal_y_type goal_y;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dwa::GoalRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwa::GoalRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalRequestResponse_

typedef ::dwa::GoalRequestResponse_<std::allocator<void> > GoalRequestResponse;

typedef boost::shared_ptr< ::dwa::GoalRequestResponse > GoalRequestResponsePtr;
typedef boost::shared_ptr< ::dwa::GoalRequestResponse const> GoalRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwa::GoalRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwa::GoalRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dwa

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dwa::GoalRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwa::GoalRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwa::GoalRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwa::GoalRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwa::GoalRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwa::GoalRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwa::GoalRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fef0002ac8ab89f12f4a92a7037d505";
  }

  static const char* value(const ::dwa::GoalRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fef0002ac8ab89fULL;
  static const uint64_t static_value2 = 0x12f4a92a7037d505ULL;
};

template<class ContainerAllocator>
struct DataType< ::dwa::GoalRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwa/GoalRequestResponse";
  }

  static const char* value(const ::dwa::GoalRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwa::GoalRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 goal_x\n\
int64 goal_y\n\
bool success\n\
";
  }

  static const char* value(const ::dwa::GoalRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwa::GoalRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwa::GoalRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwa::GoalRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.goal_y);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWA_MESSAGE_GOALREQUESTRESPONSE_H
