// Generated by gencpp from file dwa/GoalCompletion.msg
// DO NOT EDIT!


#ifndef DWA_MESSAGE_GOALCOMPLETION_H
#define DWA_MESSAGE_GOALCOMPLETION_H

#include <ros/service_traits.h>


#include <dwa/GoalCompletionRequest.h>
#include <dwa/GoalCompletionResponse.h>


namespace dwa
{

struct GoalCompletion
{

typedef GoalCompletionRequest Request;
typedef GoalCompletionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalCompletion
} // namespace dwa


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dwa::GoalCompletion > {
  static const char* value()
  {
    return "14abb92b206f3d51f81cd4863d4d4a6e";
  }

  static const char* value(const ::dwa::GoalCompletion&) { return value(); }
};

template<>
struct DataType< ::dwa::GoalCompletion > {
  static const char* value()
  {
    return "dwa/GoalCompletion";
  }

  static const char* value(const ::dwa::GoalCompletion&) { return value(); }
};


// service_traits::MD5Sum< ::dwa::GoalCompletionRequest> should match 
// service_traits::MD5Sum< ::dwa::GoalCompletion > 
template<>
struct MD5Sum< ::dwa::GoalCompletionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::GoalCompletion >::value();
  }
  static const char* value(const ::dwa::GoalCompletionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::GoalCompletionRequest> should match 
// service_traits::DataType< ::dwa::GoalCompletion > 
template<>
struct DataType< ::dwa::GoalCompletionRequest>
{
  static const char* value()
  {
    return DataType< ::dwa::GoalCompletion >::value();
  }
  static const char* value(const ::dwa::GoalCompletionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dwa::GoalCompletionResponse> should match 
// service_traits::MD5Sum< ::dwa::GoalCompletion > 
template<>
struct MD5Sum< ::dwa::GoalCompletionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::GoalCompletion >::value();
  }
  static const char* value(const ::dwa::GoalCompletionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::GoalCompletionResponse> should match 
// service_traits::DataType< ::dwa::GoalCompletion > 
template<>
struct DataType< ::dwa::GoalCompletionResponse>
{
  static const char* value()
  {
    return DataType< ::dwa::GoalCompletion >::value();
  }
  static const char* value(const ::dwa::GoalCompletionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DWA_MESSAGE_GOALCOMPLETION_H
