// Generated by gencpp from file dwa/GoalRequest.msg
// DO NOT EDIT!


#ifndef DWA_MESSAGE_GOALREQUEST_H
#define DWA_MESSAGE_GOALREQUEST_H

#include <ros/service_traits.h>


#include <dwa/GoalRequestRequest.h>
#include <dwa/GoalRequestResponse.h>


namespace dwa
{

struct GoalRequest
{

typedef GoalRequestRequest Request;
typedef GoalRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalRequest
} // namespace dwa


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dwa::GoalRequest > {
  static const char* value()
  {
    return "f89d6f624961c5b5db599ef712099bcc";
  }

  static const char* value(const ::dwa::GoalRequest&) { return value(); }
};

template<>
struct DataType< ::dwa::GoalRequest > {
  static const char* value()
  {
    return "dwa/GoalRequest";
  }

  static const char* value(const ::dwa::GoalRequest&) { return value(); }
};


// service_traits::MD5Sum< ::dwa::GoalRequestRequest> should match 
// service_traits::MD5Sum< ::dwa::GoalRequest > 
template<>
struct MD5Sum< ::dwa::GoalRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::GoalRequest >::value();
  }
  static const char* value(const ::dwa::GoalRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::GoalRequestRequest> should match 
// service_traits::DataType< ::dwa::GoalRequest > 
template<>
struct DataType< ::dwa::GoalRequestRequest>
{
  static const char* value()
  {
    return DataType< ::dwa::GoalRequest >::value();
  }
  static const char* value(const ::dwa::GoalRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dwa::GoalRequestResponse> should match 
// service_traits::MD5Sum< ::dwa::GoalRequest > 
template<>
struct MD5Sum< ::dwa::GoalRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::GoalRequest >::value();
  }
  static const char* value(const ::dwa::GoalRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::GoalRequestResponse> should match 
// service_traits::DataType< ::dwa::GoalRequest > 
template<>
struct DataType< ::dwa::GoalRequestResponse>
{
  static const char* value()
  {
    return DataType< ::dwa::GoalRequest >::value();
  }
  static const char* value(const ::dwa::GoalRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DWA_MESSAGE_GOALREQUEST_H
