// Generated by gencpp from file dwa/goal_request.msg
// DO NOT EDIT!


#ifndef DWA_MESSAGE_GOAL_REQUEST_H
#define DWA_MESSAGE_GOAL_REQUEST_H

#include <ros/service_traits.h>


#include <dwa/goal_requestRequest.h>
#include <dwa/goal_requestResponse.h>


namespace dwa
{

struct goal_request
{

typedef goal_requestRequest Request;
typedef goal_requestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goal_request
} // namespace dwa


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dwa::goal_request > {
  static const char* value()
  {
    return "499690bc96645941011b473b24eb20ab";
  }

  static const char* value(const ::dwa::goal_request&) { return value(); }
};

template<>
struct DataType< ::dwa::goal_request > {
  static const char* value()
  {
    return "dwa/goal_request";
  }

  static const char* value(const ::dwa::goal_request&) { return value(); }
};


// service_traits::MD5Sum< ::dwa::goal_requestRequest> should match 
// service_traits::MD5Sum< ::dwa::goal_request > 
template<>
struct MD5Sum< ::dwa::goal_requestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::goal_request >::value();
  }
  static const char* value(const ::dwa::goal_requestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::goal_requestRequest> should match 
// service_traits::DataType< ::dwa::goal_request > 
template<>
struct DataType< ::dwa::goal_requestRequest>
{
  static const char* value()
  {
    return DataType< ::dwa::goal_request >::value();
  }
  static const char* value(const ::dwa::goal_requestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dwa::goal_requestResponse> should match 
// service_traits::MD5Sum< ::dwa::goal_request > 
template<>
struct MD5Sum< ::dwa::goal_requestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dwa::goal_request >::value();
  }
  static const char* value(const ::dwa::goal_requestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwa::goal_requestResponse> should match 
// service_traits::DataType< ::dwa::goal_request > 
template<>
struct DataType< ::dwa::goal_requestResponse>
{
  static const char* value()
  {
    return DataType< ::dwa::goal_request >::value();
  }
  static const char* value(const ::dwa::goal_requestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DWA_MESSAGE_GOAL_REQUEST_H
