(cl:defpackage dwa-srv
  (:use )
  (:export
   "GOALCOMPLETION"
   "<GOALCOMPLETION-REQUEST>"
   "GOALCOMPLETION-REQUEST"
   "<GOALCOMPLETION-RESPONSE>"
   "GOALCOMPLETION-RESPONSE"
   "GOALREQUEST"
   "<GOALREQUEST-REQUEST>"
   "GOALREQUEST-REQUEST"
   "<GOALREQUEST-RESPONSE>"
   "GOALREQUEST-RESPONSE"
  ))

