(cl:defpackage warehouse_manager-srv
  (:use )
  (:export
   "ROBOT_TASK_COMPLETE"
   "<ROBOT_TASK_COMPLETE-REQUEST>"
   "ROBOT_TASK_COMPLETE-REQUEST"
   "<ROBOT_TASK_COMPLETE-RESPONSE>"
   "ROBOT_TASK_COMPLETE-RESPONSE"
   "ROBOT_TASK_REQUEST"
   "<ROBOT_TASK_REQUEST-REQUEST>"
   "ROBOT_TASK_REQUEST-REQUEST"
   "<ROBOT_TASK_REQUEST-RESPONSE>"
   "ROBOT_TASK_REQUEST-RESPONSE"
  ))

