// Generated by gencpp from file warehouse_manager/Robot_Task_Complete.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_COMPLETE_H
#define WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_COMPLETE_H

#include <ros/service_traits.h>


#include <warehouse_manager/Robot_Task_CompleteRequest.h>
#include <warehouse_manager/Robot_Task_CompleteResponse.h>


namespace warehouse_manager
{

struct Robot_Task_Complete
{

typedef Robot_Task_CompleteRequest Request;
typedef Robot_Task_CompleteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Task_Complete
} // namespace warehouse_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_Complete > {
  static const char* value()
  {
    return "d97d7930a530aa4c1ce9a0a5e1c268f1";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_Complete&) { return value(); }
};

template<>
struct DataType< ::warehouse_manager::Robot_Task_Complete > {
  static const char* value()
  {
    return "warehouse_manager/Robot_Task_Complete";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_Complete&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_CompleteRequest> should match 
// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_Complete > 
template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_CompleteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_manager::Robot_Task_Complete >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_CompleteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_manager::Robot_Task_CompleteRequest> should match 
// service_traits::DataType< ::warehouse_manager::Robot_Task_Complete > 
template<>
struct DataType< ::warehouse_manager::Robot_Task_CompleteRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse_manager::Robot_Task_Complete >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_CompleteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_CompleteResponse> should match 
// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_Complete > 
template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_CompleteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_manager::Robot_Task_Complete >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_CompleteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_manager::Robot_Task_CompleteResponse> should match 
// service_traits::DataType< ::warehouse_manager::Robot_Task_Complete > 
template<>
struct DataType< ::warehouse_manager::Robot_Task_CompleteResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse_manager::Robot_Task_Complete >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_CompleteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_COMPLETE_H
