// Generated by gencpp from file warehouse_manager/Robot_Task_Request.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUEST_H
#define WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUEST_H

#include <ros/service_traits.h>


#include <warehouse_manager/Robot_Task_RequestRequest.h>
#include <warehouse_manager/Robot_Task_RequestResponse.h>


namespace warehouse_manager
{

struct Robot_Task_Request
{

typedef Robot_Task_RequestRequest Request;
typedef Robot_Task_RequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Task_Request
} // namespace warehouse_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_Request > {
  static const char* value()
  {
    return "77322248a0582fccda2d5e89f799e25b";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_Request&) { return value(); }
};

template<>
struct DataType< ::warehouse_manager::Robot_Task_Request > {
  static const char* value()
  {
    return "warehouse_manager/Robot_Task_Request";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_Request&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_RequestRequest> should match 
// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_Request > 
template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_RequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_manager::Robot_Task_Request >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_RequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_manager::Robot_Task_RequestRequest> should match 
// service_traits::DataType< ::warehouse_manager::Robot_Task_Request > 
template<>
struct DataType< ::warehouse_manager::Robot_Task_RequestRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse_manager::Robot_Task_Request >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_RequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_RequestResponse> should match 
// service_traits::MD5Sum< ::warehouse_manager::Robot_Task_Request > 
template<>
struct MD5Sum< ::warehouse_manager::Robot_Task_RequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_manager::Robot_Task_Request >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_RequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_manager::Robot_Task_RequestResponse> should match 
// service_traits::DataType< ::warehouse_manager::Robot_Task_Request > 
template<>
struct DataType< ::warehouse_manager::Robot_Task_RequestResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse_manager::Robot_Task_Request >::value();
  }
  static const char* value(const ::warehouse_manager::Robot_Task_RequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUEST_H
