// Generated by gencpp from file warehouse_manager/Robot_Task_RequestResponse.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUESTRESPONSE_H
#define WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehouse_manager
{
template <class ContainerAllocator>
struct Robot_Task_RequestResponse_
{
  typedef Robot_Task_RequestResponse_<ContainerAllocator> Type;

  Robot_Task_RequestResponse_()
    : x(0.0)
    , y(0.0)
    , task_available(false)  {
    }
  Robot_Task_RequestResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , task_available(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _task_available_type;
  _task_available_type task_available;





  typedef boost::shared_ptr< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Robot_Task_RequestResponse_

typedef ::warehouse_manager::Robot_Task_RequestResponse_<std::allocator<void> > Robot_Task_RequestResponse;

typedef boost::shared_ptr< ::warehouse_manager::Robot_Task_RequestResponse > Robot_Task_RequestResponsePtr;
typedef boost::shared_ptr< ::warehouse_manager::Robot_Task_RequestResponse const> Robot_Task_RequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace warehouse_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'warehouse_manager': ['/home/siddhesh/warehouse_sim/warehouse_dwa_final/src/warehouse_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7c4051d2307bca9981d8732c7b53196";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7c4051d2307bca9ULL;
  static const uint64_t static_value2 = 0x981d8732c7b53196ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_manager/Robot_Task_RequestResponse";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
bool task_available\n\
";
  }

  static const char* value(const ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.task_available);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Robot_Task_RequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_manager::Robot_Task_RequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "task_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_available);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_MANAGER_MESSAGE_ROBOT_TASK_REQUESTRESPONSE_H
